FROM node:22.15.0

WORKDIR /dashboard

COPY ui/node/package*.json ./

# npm install next@latest react@latest react-dom@latest typescript @types/react tailwindcss @tailwindcss/postcss postcss
# npm install next@latest react@latest react-dom@latest typescript @types/react 
RUN npm install next@latest \
        react@latest \
        react-dom@latest \
        typescript \
        @types/react 

RUN npm install -D tailwindcss \
        @tailwindcss/postcss \
        postcss \
        autoprefixer

# COPY ui/node/ .

CMD ["npm", "run", "dev"]
