FROM python:3.10.12

USER root
WORKDIR /tech

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY pipelines/technicals/ pipelines/technicals/
COPY util/postgres/ util/postgres/
COPY util/*.py util/
COPY util/logger/ util/logger/
COPY *.env .

ENV INDOCKER=True

ENTRYPOINT python pipelines/technicals/technicals_ingest.py