FROM python:3.10.12

USER root
WORKDIR /pr

COPY pipelines/press_releases/requirements.txt /pr/requirements.txt
RUN pip install "setuptools<58.0.0"
RUN python -m pip install -r requirements.txt

COPY pipelines/press_releases/* /pr/pipelines/press_releases/
COPY util/ /pr/util/
COPY *.env /pr/

ENV INDOCKER=True

WORKDIR /pr/pipelines/press_releases/
ENTRYPOINT python newswire_client.py
# ["tail", "-f", "/dev/null"]
