FROM python:3.10-bullseye

USER root
WORKDIR /press_releases

COPY requirements.txt .

RUN python -m pip install -r requirements.txt

COPY pipelines/press_releases/* /press_releases/pipelines/press_releases/
COPY util/elastic/* /press_releases/util/elastic/
COPY util/postgres/db/* press_releases/util/postgres/db/
COPY util/crud_pg.py press_releases/util/
COPY util/requests_util.py press_releases/util/

ENTRYPOINT python newswire_client.py