FROM python:3.12.3 AS build

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
# Set environment variables for uv to not create a virtual environment in the container build stage
ENV UV_SYSTEM_PYTHON=1
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /edgar

COPY ./requirements_extract.txt requirements.txt
RUN uv pip install -r requirements.txt

FROM python:3.12.3

ARG FILING_TYPE=${FILING_TYPE}
ENV FILING_TYPE=${FILING_TYPE}
WORKDIR /edgar

# Copy installed packages from the builder stage
COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

COPY ./util/ ./util/
COPY ./pipelines/fundamentals/extract_filings/${FILING_TYPE}_df.py  pipelines/fundamentals/extract_filings/${FILING_TYPE}_df.py 
COPY ./pipelines/fundamentals/get_ticker_list.py  pipelines/fundamentals/get_ticker_list.py 
COPY *.env .env

ENV INDOCKER=True

ENTRYPOINT python pipelines/fundamentals/extract_filings/${FILING_TYPE}_df.py 
