FROM python:3.10.12

USER root
WORKDIR /edgar

COPY ./requirements_extract.txt requirements.txt
RUN python -m pip install -r requirements.txt

COPY util/ util/
COPY pipelines/fundamentals/extract_filings/facts_df.py  pipelines/fundamentals/extract_filings/facts_df.py 
COPY pipelines/fundamentals/get_ticker_list.py  pipelines/fundamentals/get_ticker_list.py 
COPY *.env .env

ENV INDOCKER=True

ENTRYPOINT python pipelines/fundamentals/extract_filings/facts_df.py 
