FROM python:3.10.12

USER root
WORKDIR /tech

COPY requirements.txt /tech/requirements.txt
RUN python -m pip install -r requirements.txt

COPY pipelines/technicals/* /tech/pipelines/technicals/
COPY util/postgres/ /tech/util/postgres/
COPY util/*.py /tech/util/*.py
COPY *.env /tech/

ENV INDOCKER=True

WORKDIR /tech/pipelines/technicals/
ENTRYPOINT python technicals_ingest.py
# ["tail", "-f", "/dev/null"]
