FROM python:3.12.3 AS build

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
# Set environment variables for uv to not create a virtual environment in the container build stage
ENV UV_SYSTEM_PYTHON=1
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /edgar

COPY ./requirements_load_filings.txt requirements.txt
RUN uv pip install -r requirements.txt

COPY util/ util/
COPY pipelines/fundamentals/load/load_raw_html.py pipelines/fundamentals/load/load_raw_html.py 
COPY *.env .env

ENV INDOCKER=True

ENTRYPOINT python pipelines/fundamentals/load/load_raw_html.py 
