services:
  vectorize:
    env_file: .env
    build: 
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - homeserver
    container_name: vectorize_filings